config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get 'order_details'
    end
  end
  resources :admins do
    member do
      get 'products_all'
      get 'product_details'
      get 'block_user'
      get 'unblock_user'
      get 'new_seller_requests'
      get 'sellers_list'
    end
  end
  resources :quantities
  resources :sizes
  resources :colours
  resources :addresses
  resources :carts
  devise_for :users, controllers: {
        registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users  
  resources :home do
    member do
      get 'check_product'
      get 'after_check_product'
    end
    collection do
      get 'welcome'
    end
  end
  resources :customers do 
    resources :carts
  end
  resources :categories
  resources :images
  resources :sellers do
    resources :products
  end
  root 'home#index'

end

app/models/address.rb
class Address < ApplicationRecord
  #relationships
  belongs_to :customer
  has_many :orders

  #validations
  validates :address, presence: true
  validates :city, :district, :pincode, presence: true
  validates :pincode, format: { with: /\(?[0-9]{6}\)?/ ,message: "should be 123456"}
end

app/models/cart.rb
class Cart < ApplicationRecord
  #relationships
  belongs_to :customer
  belongs_to :product
  belongs_to :quantity

  #scope
  scope :check_out_cart, -> {where(check_out:true)}
end

app/models/category.rb
class Category < ApplicationRecord
  #relationships
  has_many :products, dependent: :destroy
  
  #validations
  validates :category_name, presence: true
  validates_each :category_name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end

app/models/colour.rb
class Colour < ApplicationRecord
  #validations
  validates :colour, presence: true, on: :update
  #relationship
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  #relationships
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  #validation
  validates :first_name, :last_name, :phone, presence: true
  validates :first_name, :last_name, :phone, presence: true, on: :update
  validates :phone, format: { with: /\(?[0-9]{10}\)?/, message: "Phone numbers must be 10 digits"}
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  #relationships
  belongs_to :product
  belongs_to :colour
  #validations
  validates :image ,presence:  {message: "Must select"}
end

app/models/order.rb
class Order < ApplicationRecord
  #relationships
  belongs_to :payment
  belongs_to :address
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  #relationships
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  #enum
  enum status: [:unblock, :block]

  #relationships
  belongs_to :seller
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :colours, through: :quantities
  has_many :sizes, through: :quantities
  #validation
  validates :product_name, :price, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :size
  belongs_to :product
  belongs_to :colour
  has_many :carts
  #validations
  validates :quantity, presence: true
  #scopes
  scope :find_product_quantity, ->(colour, size, product) {where("colour_id = ? and size_id = ? and product_id = ?", colour, size, product).first}	
end

app/models/seller.rb
class Seller < ApplicationRecord
  #enum
  enum status: [:pending, :approved]

  #relationships
  belongs_to :user
  has_many :products, dependent: :destroy
  
  #validations
  validates :sname, presence: true,  format: { with: /\A[a-z]+\z/i }  
  validates :website, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  #relatioships
  has_many :quantities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  #enum
  enum role: [:admin, :seller, :customer]
  enum status: [:unblock, :block]

  #devise_gem
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable,:omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
         
  #relationships
  has_one :customer, dependent: :destroy
  has_one :seller, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colours_helper.rb
module ColoursHelper
  def colour_list
  	Colour.all.map{|p|[ p.colour, p.id ]}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_list
  	payments = Payment.all
  	payments.map{|p|[p.payment_method, p.id]}
  end
end

app/helpers/sizes_helper.rb
module SizesHelper
  def size_list
  	Size.all.map{|p|[ p.size, p.id ]}
  end
end

app/views/admins/index.html.haml
.container.col-lg-9.offset-md-2
  .div.admin_border.text-center
    %h5.font_color Users
    = link_to image_tag("users.jpeg", size:"200x200", title: "Customers"), admin_path(current_user)

  .div.admin_border.text-center
    %h5.font_color Sellers
    = link_to image_tag("users.jpeg", size:"200x200", title: "Sellers"), sellers_list_admin_path(current_user)
    
  .div.admin_border.text-center
    %h5.font_color New Seller Requests
    = link_to image_tag("new_user.jpeg", size:"190x200", title: "New seller requests"),new_seller_requests_admin_path(current_user)
      
  .div.admin_border.text-center
    %h5.font_color Categories
    = link_to image_tag("Categories.jpeg", size:"235x200", title: "Categories of product"), categories_path
      
  .div.admin_border.text-center
    %h5.font_color Colours
    = link_to image_tag("colour.png", size:"230x200", title: "Colours of product"), colours_path
      
  .div.admin_border.text-center
    %h5.font_color Sizes
    = link_to image_tag("add.png", size:"200x200", title: "Sizes of product"), sizes_path
  %br/
  %br/

app/views/admins/new_seller_requests.html.haml
.container
  %table.table.table-hover
    - if @sellers.blank?
      .text-primary.seller_req
        %h4
          No new seller requests found!
    - else
      %thead
        %tr
          %th
            Name
          %th
            Email
          %th
            Website
          %th
            Action
      %tbody
        - @sellers.each do |seller|
          %tr
            %td= seller.sname
            %td= seller.user.email
            %td= seller.website
            %td
              = link_to image_tag("approve.png", size:"40x40", title: "Click to approve the Seller"),admin_path(seller: seller), method: :put
  = will_paginate @sellers, class: :flickr_pagination

app/views/admins/product_details.html.haml
.container
  %table.table.table-hover
    %tr
      %td
      %td
        - @images.limit(1).each do |form|
          = image_tag (form.image.thumb.url), class: :picture
        
      %td
    %tr
      %td
        %strong ProductName:
      %td
      %td
        = @product.product_name

    %tr
      %td
        %strong Category:
      %td
      %td
        = @product.category.category_name
    %tr
      %td
        %strong Price:
      %td
      %td
        = @product.price
    %tr
      %td
        %strong Colours:
      %td
      %td
        - @product.colours.distinct.each do |colour|
          = colour.colour
          %br/
    %tr
      %td
        %strong Sizes:
      %td
      %td
        - @product.sizes.distinct.each do |size|
          = size.size
          %br/
    %tr
      %td
        %strong Available:
      %td
      %td
        = @product.quantity
    %tr
      %td
        %strong Sold:
      %td
      %td
        = @product.sold   

app/views/admins/products_all.html.haml
.container
  %table.table.table-hover
    %thead
      %tr
        %th Product Name
        %th Category
        %th Price
        %th Sold
        %th Actions
        %th
    %tbody
      - @products.each do |product|
        %tr
          %td= product.product_name
          %td= product.category.category_name
          %td
            ₹
            = product.price
          %td= product.sold
          %td= link_to image_tag("view.png", size:"25x25"), product_details_admin_path(product)
          %td
            - if product.unblock?
              = link_to image_tag("unblock.png", size:"25x25"), block_user_admin_path(product: product)
            - else
              = link_to image_tag("block.png", size:"25x25"),unblock_user_admin_path(product: product)
  = will_paginate @products, class: :flickr_pagination

app/views/admins/sellers_list.html.haml
.container
  %table.table.table-hover
    %thead
      %tr
        %th.font_color
          Sellers
        %th.font_color
          Email
        %th.font_color
          Status
        %th.font_color
          Products
        %th
        %th.font_color
          Actions
        %th
        %th
    %tbody
      - @sellers.each do |seller|
        %tr
          %td= seller.sname
          %td= seller.user.email
          %td
            - unless seller.approved?
              = link_to image_tag("approve.png", size:"30x30", title: "Click to approve the Seller"), admin_path(seller: seller), method: :put
            - else
              approved
              
          %td= seller.products.count
          %td= link_to 'view', products_all_admin_path(seller: seller)
          %td
            - if seller.user.unblock?
              = link_to image_tag("unblock.png", size:"25x25", title: "Click to Block the User"), block_user_admin_path(user: seller.user)
            - else
              = link_to image_tag("block.png", size:"25x25", title: "Click to Unblock the User"),unblock_user_admin_path(user: seller.user)
          %td= link_to image_tag("vprofile.jpeg", size:"25x25", title: "Click to View Profile"), seller_path(seller)
          %td= link_to image_tag("delete.png", size:"25x25", title: "Click to Delete the User"), user_registration_path(user: seller.user), method: :delete, data: { confirm: 'Are you sure?' }
  = will_paginate @sellers, class: :flickr_pagination

app/views/admins/show.html.haml
.container
  %table.table.table-hover
    %thead
      %tr
        %th.font_color
          Customers
        %th          
        %th.font_color
          Email
        %th.font_color
          Orders
        %th.font_color
          Actions
        %th
        %th
    %tbody
      - @customers.each do |customer|
        %tr
          %td= customer.first_name
          %td= customer.last_name
          %td= customer.user.email
          %td= customer.orders.count
          - if customer.user.unblock?
            %td= link_to image_tag("unblock.png", size:"25x25", title: "Click to Block the User"),block_user_admin_path(user: customer.user)
          - else
            %td= link_to image_tag("block.png", size:"25x25", title: "Click to Unblock the User"),unblock_user_admin_path(user: customer.user)
          %td= link_to image_tag("vprofile.jpeg", size:"25x25", title: "Click to View Profile"), customer_path(customer)
          %td
            = link_to image_tag("delete.png", size:"25x25", title: "Click to Delete the User"), user_registration_path(user: customer.user), method: :delete, data: { confirm: 'Are you sure?' }
  %br/
  %br/

  = will_paginate @customers, class: :flickr_pagination

app/views/shared/_error.html.haml
#error_explanation
  .container
    .field_with_errors
      - if object.errors.any?
        - for message_error in object.errors.full_messages
          %li
            #{message_error}