config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get 'order_details'
    end
  end
  resources :admins do
    member do
      get 'products_all'
      get 'product_details'
      get 'block_user'
      get 'unblock_user'
      get 'new_seller_requests'
      get 'sellers_list'
    end
  end
  resources :quantities
  resources :sizes
  resources :colours
  resources :addresses
  resources :carts
  devise_for :users, controllers: {
        registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users  
  resources :home do
    member do
      get 'check_product'
      get 'after_check_product'
    end
    collection do
      get 'welcome'
    end
  end
  resources :customers do 
    resources :carts
  end
  resources :categories
  resources :images
  resources :sellers do
    resources :products
  end
  root 'home#index'

end

app/models/address.rb
class Address < ApplicationRecord
  #relationships
  belongs_to :customer
  has_many :orders

  #validations
  validates :address, presence: true
  validates :city, :district, :pincode, presence: true
  validates :pincode, format: { with: /\(?[0-9]{6}\)?/ ,message: "should be 123456"}
end

app/models/cart.rb
class Cart < ApplicationRecord
  #relationships
  belongs_to :customer
  belongs_to :product
  belongs_to :quantity

  #scope
  scope :check_out_cart, -> {where(check_out:true)}
end

app/models/category.rb
class Category < ApplicationRecord
  #relationships
  has_many :products, dependent: :destroy
  
  #validations
  validates :category_name, presence: true
  validates_each :category_name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end

app/models/colour.rb
class Colour < ApplicationRecord
  #validations
  validates :colour, presence: true, on: :update
  #relationship
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  #relationships
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  #validation
  validates :first_name, :last_name, :phone, presence: true
  validates :first_name, :last_name, :phone, presence: true, on: :update
  validates :phone, format: { with: /\(?[0-9]{10}\)?/, message: "Phone numbers must be 10 digits"}
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  #relationships
  belongs_to :product
  belongs_to :colour
  #validations
  validates :image ,presence:  {message: "Must select"}
end

app/models/order.rb
class Order < ApplicationRecord
  #relationships
  belongs_to :payment
  belongs_to :address
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  #relationships
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  #enum
  enum status: [:unblock, :block]

  #relationships
  belongs_to :seller
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :colours, through: :quantities
  has_many :sizes, through: :quantities
  #validation
  validates :product_name, :price, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :size
  belongs_to :product
  belongs_to :colour
  has_many :carts
  #validations
  validates :quantity, presence: true
  #scopes
  scope :find_product_quantity, ->(colour, size, product) {where("colour_id = ? and size_id = ? and product_id = ?", colour, size, product).first}	
end

app/models/seller.rb
class Seller < ApplicationRecord
  #enum
  enum status: [:pending, :approved]

  #relationships
  belongs_to :user
  has_many :products, dependent: :destroy
  
  #validations
  validates :sname, presence: true,  format: { with: /\A[a-z]+\z/i }  
  validates :website, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  #relatioships
  has_many :quantities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  #enum
  enum role: [:admin, :seller, :customer]
  enum status: [:unblock, :block]

  #devise_gem
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable,:omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
         
  #relationships
  has_one :customer, dependent: :destroy
  has_one :seller, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_seller, only: [:show, :edit, :update, :destroy]
  add_breadcrumb "Home", :sellers_path, only: [:index, :new, :edit]

  def index
    unless current_user.seller
      redirect_to new_seller_path
    else
      seller = current_user.seller
      @products = seller.products.paginate(page: params[:page], per_page: 20)
      @total = @products.count
      @pending = 0
      @blocked = 0
      seller.products.each do |product|
        if product.quantity == 0
          @pending +=1
        end
        if product.block?
          @blocked +=1
        end
      end
    end
  end

  def show
    if current_user.admin?
      add_breadcrumb "Home", admins_path
      add_breadcrumb "Profile"
      @seller = Seller.find(params[:id])
    else
      add_breadcrumb "Home", sellers_path
      add_breadcrumb "Profile", seller_path(current_user.seller)
      @seller = Seller.find(params[:id])
      authorize @seller
    end
  end

  def new
    @seller = Seller.new
  end

  def edit
    unless current_user.seller
      redirect_to new_seller_path
    end
  end

  def create
    @seller = current_user.create_seller(seller_params)
    if @seller.save
      flash[:success] = 'Profile successfully added.'
      redirect_to seller_path(@seller)
    else
      flash[:error] = 'Something went wrong!! Please Try again!!!'
      render 'new'
    end
  end

  def update
    if @seller.update(seller_params)
      flash[:notice] = 'Profile successfully updated.'
      redirect_to seller_path(current_user.seller)
    else
      flash[:error] = 'Something went wrong!! Please Try again!!!'
      render 'edit'
    end
  end

  def destroy
    if @seller.destroy
      flash[:error] = "Your account has been removed"
    else
      flash[:error] = "Your account can not be removed"
    end
  end

  private
    def set_seller
      @seller = current_user.seller
    end 

    def seller_params
      params.require(:seller).permit(:sname, :website, :description)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colours_helper.rb
module ColoursHelper
  def colour_list
  	Colour.all.map{|p|[ p.colour, p.id ]}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_list
  	payments = Payment.all
  	payments.map{|p|[p.payment_method, p.id]}
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
  def size_list
  	Size.all.map{|p|[ p.size, p.id ]}
  end
end

app/views/sellers/_form.html.haml
= form_with(model: @seller, local: true) do |form|
  = render 'shared/error', object: @seller
  %table.table.table-hover
    %tr
      %td 
        Name:
      %td
        = form.text_field :sname
    %tr
      %td
        Website:
      %td
        = form.url_field :website, value: "https://www."
    %tr
      %td 
        About me:
      %td
        = form.text_field :description
    %tr
      %td
        = form.submit "save"

app/views/sellers/edit.html.haml
.container
  = render 'form', seller: @seller
  %br/
  = link_to image_tag("back.jpeg", size:"40x40"), sellers_path
  .pull-right
    = link_to image_tag("vprofile.jpeg", size:"50x50"), seller_path(current_user.seller) 

app/views/sellers/index.html.haml
.container
  %table.table.table-hover
    - if @products.blank?
      %h3.text-secondary
        No Products Added.
    - else
      %tbody
        - @products.each do |product|
          - product.images.limit(1).each do |form|
            .display.border.border-black
              .text-center
                = link_to seller_product_path(current_user.seller, product) do 
                  = image_tag (form.image.thumb.url), class: :picture
                %br/
                = truncate(product.product_name, length: 20)
                %br/
                - if product.unblock?
                  .font_color
                    Available:
                    = product.quantity
                    &nbsp
                    Sold:
                    = product.sold
                - else
                  = image_tag "blocked.jpg", size:"20x20", title: "Product is Blocked by Admin"
  #topbutton.font_color
    = link_to 'Products', seller_products_path(current_user.seller)
    .span.badge.badge-primary
      = @total
    Pending
    .span.badge.badge-primary
      = @pending
    Blocked
    .span.badge.badge-primary
      = @blocked
  = will_paginate @products, class: :flickr_pagination

app/views/sellers/new.html.haml
.container
  %h4
    Create your profile
  %br/
  = render 'form', seller: @seller
  = link_to 'Back', sellers_path

app/views/sellers/show.html.haml
.container
  %table.table.table-hover
    %tr   
      %td
        %strong Name:
      %td
        = @seller.sname
    %tr   
      %td
        %strong Website:
      %td
        = @seller.website
    %tr   
      %td
        %strong About:
      %td
        = @seller.description
  - unless current_user.admin?
    .pull-right
      = link_to image_tag("edit.png", size:"40x40"), edit_seller_path(current_user)
    = link_to image_tag("back.jpeg", size:"40x40"), sellers_path