config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get 'order_details'
    end
  end
  resources :admins do
    member do
      get 'products_all'
      get 'product_details'
      get 'block_user'
      get 'unblock_user'
      get 'new_seller_requests'
      get 'sellers_list'
    end
  end
  resources :quantities
  resources :sizes
  resources :colours
  resources :addresses
  resources :carts
  devise_for :users, controllers: {
        registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users  
  resources :home do
    member do
      get 'check_product'
      get 'after_check_product'
    end
    collection do
      get 'welcome'
    end
  end
  resources :customers do 
    resources :carts
  end
  resources :categories
  resources :images
  resources :sellers do
    resources :products
  end
  root 'home#index'

end

app/models/address.rb
class Address < ApplicationRecord
  #relationships
  belongs_to :customer
  has_many :orders

  #validations
  validates :address, presence: true
  validates :city, :district, :pincode, presence: true
  validates :pincode, format: { with: /\(?[0-9]{6}\)?/ ,message: "should be 123456"}
end

app/models/cart.rb
class Cart < ApplicationRecord
  #relationships
  belongs_to :customer
  belongs_to :product
  belongs_to :quantity

  #scope
  scope :check_out_cart, -> {where(check_out:true)}
end

app/models/category.rb
class Category < ApplicationRecord
  #relationships
  has_many :products, dependent: :destroy
  
  #validations
  validates :category_name, presence: true
  validates_each :category_name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end

app/models/colour.rb
class Colour < ApplicationRecord
  #validations
  validates :colour, presence: true, on: :update
  #relationship
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  #relationships
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  #validation
  validates :first_name, :last_name, :phone, presence: true
  validates :first_name, :last_name, :phone, presence: true, on: :update
  validates :phone, format: { with: /\(?[0-9]{10}\)?/, message: "Phone numbers must be 10 digits"}
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  #relationships
  belongs_to :product
  belongs_to :colour
  #validations
  validates :image ,presence:  {message: "Must select"}
end

app/models/order.rb
class Order < ApplicationRecord
  #relationships
  belongs_to :payment
  belongs_to :address
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  #relationships
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  #enum
  enum status: [:unblock, :block]

  #relationships
  belongs_to :seller
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :colours, through: :quantities
  has_many :sizes, through: :quantities
  #validation
  validates :product_name, :price, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :size
  belongs_to :product
  belongs_to :colour
  has_many :carts
  #validations
  validates :quantity, presence: true
  #scopes
  scope :find_product_quantity, ->(colour, size, product) {where("colour_id = ? and size_id = ? and product_id = ?", colour, size, product).first}	
end

app/models/seller.rb
class Seller < ApplicationRecord
  #enum
  enum status: [:pending, :approved]

  #relationships
  belongs_to :user
  has_many :products, dependent: :destroy
  
  #validations
  validates :sname, presence: true,  format: { with: /\A[a-z]+\z/i }  
  validates :website, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  #relatioships
  has_many :quantities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  #enum
  enum role: [:admin, :seller, :customer]
  enum status: [:unblock, :block]

  #devise_gem
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable,:omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
         
  #relationships
  has_one :customer, dependent: :destroy
  has_one :seller, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  add_breadcrumb "Home", :root_path, only: [:show, :after_check_product, :index]
  add_breadcrumb "Product", :home_path, only: [:show, :after_check_product]
  
  def welcome
  end

  def show
    @product = Product.find(params[:id])
    @quantities = @product.quantities 
    @images = @product.images
    @colours = @product.colours.distinct
    @sizes = @product.sizes.distinct
  end

  def after_check_product    
    @quantity = Quantity.find(params[:quantity])
    @product = Product.find(params[:id])
    @images = @product.images.where(colour_id: @quantity.colour_id)
    add_breadcrumb @product.product_name, after_check_product_home_path
  end


  def check_product
    colour = params[:colour_id]
    size = params[:size_id]
    product = params[:product_id]
    @quantity = Quantity.find_product_quantity(colour, size, product)
    begin
      if @quantity.quantity >=1
        flash[:notice] = "product is available"
        redirect_to after_check_product_home_path(product, quantity: @quantity.id)
      else
        flash[:error] = "Product is out of stock"
        redirect_to home_path
      end
    rescue
      flash[:error] = "Sorry!! Product not available, Search for different colours and size"
      redirect_to home_path
    end
  end

  def index
    if user_signed_in?
      unless current_user.seller?
        unless current_user.admin?
          unless current_user.customer
            redirect_to new_customer_path
          end
        end
      end
    end
    category = params[:category]
    unless category
      @products = Product.where("quantity > ? and status = ?", 0, 0).paginate(page: params[:page], per_page: 20)
    else
      @category = Category.find_by(category_name: params[:category])
      @products = @category.products.where("quantity > ? and status = ?", 0, 0).paginate(page: params[:page], per_page: 20)
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colours_helper.rb
module ColoursHelper
  def colour_list
  	Colour.all.map{|p|[ p.colour, p.id ]}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_list
  	payments = Payment.all
  	payments.map{|p|[p.payment_method, p.id]}
  end
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
  def size_list
  	Size.all.map{|p|[ p.size, p.id ]}
  end
end

app/views/home/after_check_product.html.haml
.container
  %table.table.table-hover
    %tr
      %td
        %strong ProductName:
      %td
        = @product.product_name
    %tr
      %td
        %strong Category:
      %td
        = @product.category.category_name
    %tr
      %td
        %strong Price:
      %td
        = @product.price
    %tr
      %td
        %strong Available Quantity:
      %td
        = @quantity.quantity
    %tr
      %td
        #{@product.product_name} will be delivered within 
        =from_time = DateTime.now.to_date + 5.days

    - @images.each do |form|
      = link_to (form.image.thumb.url), data: { lightbox: 'roadtrip', title: 'Product Image'}  do
        = image_tag (form.image.thumb.url), alt: 'logo', class: :pictur
    - if user_signed_in?
      - if current_user.customer
        .text-right
          .btn.btn-ash
            = link_to 'Add to Cart',   customer_carts_path(current_user.customer, product_id: @product.id, quantity: @quantity), method: :post
    - else
      .text-right
        .btn.btn-ash
          = link_to 'Add to Cart',new_user_session_path, flash_notice: "please sign in to continue"

app/views/home/index.html.haml
.container
  %table.table.table-hover
    %tbody
      - @products.each do |product|
        - if product.seller.user.unblock?
          - product.images.limit(1).each do |form|
            .display.border.border-white
              .text-center
                = link_to home_path(product) do
                  = image_tag (form.image.thumb.url), class: :picture
                %br/
                = truncate(product.product_name, length: 20)
                %br/
                Price:
                ₹
                = product.price
  = will_paginate @products, class: :flickr_pagination

app/views/home/show.html.haml
.container
  = form_with(url: check_product_home_path, method: :get, local: true) do |form|
    %table.table.table-hover
      %tr
        %td
          %strong ProductName:
        %td
          = @product.product_name
      %tr
        %td
          %strong Category:
        %td
          = @product.category.category_name
      %tr
        %td
          %strong Price:
        %td
          = @product.price
      - @images.limit(4).each do |form|
        = link_to (form.image.thumb.url), data: { lightbox: 'roadtrip', title: @product.product_name}  do
          = image_tag (form.image.thumb.url), class: "pictur #{form.colour.id}"
      %tr
        %td
          Colour:
        %td
          = form.select :colour_id, @colours.collect {|p| [ p.colour, p.id ] }
      %tr
        %td
          Size:
        %td
          - if @sizes.size == 1 && @sizes.first.size == ""
            = "-"
            = form.hidden_field :size_id, value: 1
          - else
            = form.select(:size_id, @sizes.collect {|p| [ p.size, p.id ] })          
      %tr
        %td
          = form.hidden_field :product_id, value: @product.id
    #mybutton
      = form.submit "Search", class: "btn btn-ash"
  %h5
    =link_to 'Back',root_path

app/views/home/welcome.html.haml
.container
  .h1.text-center.font_color
    Welcome to the Webcart
    %br/
    .btn.btn-ash.fixed-bottom_button
      = link_to 'Continue shopping',root_path