config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    member do
      get 'order_details'
    end
  end
  resources :admins do
    member do
      get 'products_all'
      get 'product_details'
      get 'block_user'
      get 'unblock_user'
      get 'new_seller_requests'
      get 'sellers_list'
    end
  end
  resources :quantities
  resources :sizes
  resources :colours
  resources :addresses
  resources :carts
  devise_for :users, controllers: {
        registrations: 'users/registrations', sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users  
  resources :home do
    member do
      get 'check_product'
      get 'after_check_product'
    end
    collection do
      get 'welcome'
    end
  end
  resources :customers do 
    resources :carts
  end
  resources :categories
  resources :images
  resources :sellers do
    resources :products
  end
  root 'home#index'

end

app/models/address.rb
class Address < ApplicationRecord
  #relationships
  belongs_to :customer
  has_many :orders

  #validations
  validates :address, presence: true
  validates :city, :district, :pincode, presence: true
  validates :pincode, format: { with: /\(?[0-9]{6}\)?/ ,message: "should be 123456"}
end

app/models/cart.rb
class Cart < ApplicationRecord
  #relationships
  belongs_to :customer
  belongs_to :product
  belongs_to :quantity

  #scope
  scope :check_out_cart, -> {where(check_out:true)}
end

app/models/category.rb
class Category < ApplicationRecord
  #relationships
  has_many :products, dependent: :destroy
  
  #validations
  validates :category_name, presence: true
  validates_each :category_name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end

app/models/colour.rb
class Colour < ApplicationRecord
  #validations
  validates :colour, presence: true, on: :update
  #relationship
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  #relationships
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  #validation
  validates :first_name, :last_name, :phone, presence: true
  validates :first_name, :last_name, :phone, presence: true, on: :update
  validates :phone, format: { with: /\(?[0-9]{10}\)?/, message: "Phone numbers must be 10 digits"}
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
  #relationships
  belongs_to :product
  belongs_to :colour
  #validations
  validates :image ,presence:  {message: "Must select"}
end

app/models/order.rb
class Order < ApplicationRecord
  #relationships
  belongs_to :payment
  belongs_to :address
  belongs_to :customer
end

app/models/payment.rb
class Payment < ApplicationRecord
  #relationships
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  #enum
  enum status: [:unblock, :block]

  #relationships
  belongs_to :seller
  belongs_to :category
  has_many :carts, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :quantities, dependent: :destroy
  has_many :colours, through: :quantities
  has_many :sizes, through: :quantities
  #validation
  validates :product_name, :price, presence: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1000000 }
end

app/models/quantity.rb
class Quantity < ApplicationRecord
  belongs_to :size
  belongs_to :product
  belongs_to :colour
  has_many :carts
  #validations
  validates :quantity, presence: true
  #scopes
  scope :find_product_quantity, ->(colour, size, product) {where("colour_id = ? and size_id = ? and product_id = ?", colour, size, product).first}	
end

app/models/seller.rb
class Seller < ApplicationRecord
  #enum
  enum status: [:pending, :approved]

  #relationships
  belongs_to :user
  has_many :products, dependent: :destroy
  
  #validations
  validates :sname, presence: true,  format: { with: /\A[a-z]+\z/i }  
  validates :website, presence: true
end

app/models/size.rb
class Size < ApplicationRecord
  #relatioships
  has_many :quantities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  #enum
  enum role: [:admin, :seller, :customer]
  enum status: [:unblock, :block]

  #devise_gem
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable,:omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
         
  #relationships
  has_one :customer, dependent: :destroy
  has_one :seller, dependent: :destroy

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  add_breadcrumb "Home", :sellers_path

  def index
    add_breadcrumb "Products", seller_products_path(current_user.seller)
    @seller = current_user.seller
    @products = @seller.products.paginate(page: params[:page], per_page: 20)
  end

  def new
    add_breadcrumb "New Product", new_seller_product_path(current_user.seller)
    @product = Product.new
    @categories = Category.all
    @sizes = Size.all
  end

  def show 
    @product = Product.find(params[:id])
    @images = @product.images
    add_breadcrumb @product.product_name, seller_product_path(current_user.seller)
  end

  def edit
  end

  def create 
    seller = current_user.seller
    @product = seller.products.new(product_params)
    if @product.save
      flash[:success] = 'Product successfully added.'
      redirect_to new_quantity_path(product: @product)
    else
      flash[:error] = 'Something went wrong!! Please Try again!!!'
      @categories = Category.all
      render 'new'
    end
  end

  def update
  end

  def destroy
    if @product.destroy
      flash[:error] = 'Product successfully removed.'
    else
      flash[:error] = 'Product not removed!!! Try Again'
    end
    redirect_to seller_products_path
  end

  private
    def set_product 
      @product = Product.find(params[:id])
    end
    
    def product_params
      params.require(:product).permit(:product_name, :about, :price, :quantity, :category_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colours_helper.rb
module ColoursHelper
  def colour_list
  	Colour.all.map{|p|[ p.colour, p.id ]}
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def payment_list
  	payments = Payment.all
  	payments.map{|p|[p.payment_method, p.id]}
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
  def size_list
  	Size.all.map{|p|[ p.size, p.id ]}
  end
end

app/views/products/index.html.haml
.container
  %table.table.table-hover
    %thead
      %tr
        %th Product Name
        %th Details
        %th Price
        %th Category
        %th Sold
        %th Actions
        %th
        %th{:colspan => "3"}
    %tbody
      - @products.each do |product|
        %tr
          %td= product.product_name
          %td= product.about
          %td= product.price
          %td= product.category.category_name
          %td.font_color
            = product.sold
            \/
            = product.quantity
          %td= link_to image_tag("info.png", size:"25x25", title: "View Details"), seller_product_path(current_user.seller, product)
          %td= link_to image_tag("addimg.jpeg", size:"25x25", title: "Add Images"), new_image_path(product: product)
          %td= link_to image_tag("delete.png", size:"25x25", title: "Delete Product"), seller_product_path(current_user.seller,product), method: :delete,data: { confirm: 'Are you sure?' }
          %td
            - if product.images.blank?
              Images not added
          %td
            - if product.block?
              = image_tag "blocked.jpg", size:"20x20", title: "Product is Blocked by Admin"
  .btn.btn-ash#topbutton
    = link_to 'Add new product', new_seller_product_path
  = link_to 'Back', sellers_path
  = will_paginate @products, class: :flickr_pagination

app/views/products/new.html.haml
.container
  %h4 Add Products
  = form_with(model: @product, url:seller_products_path, local: true) do |form|
    = render 'shared/error', object: @product
    %table.table
      %tr
        %td 
          Product Name:
        %td
          = form.text_field :product_name, class: :'form-control', required: true
      %tr
        %td 
          Description:
        %td
          = form.text_field :about, class: :'form-control', required: true
      %tr
        %td
          Price:
        %td
          = form.text_field :price, class: :'form-control', required: true
      %tr
        %td
          Category:
        %td
          = form.select(:category_id, category_list)
      %tr
        %td
          .actions
            = form.submit :Save
  = link_to 'View Products', seller_products_path

app/views/products/products_all.html.haml
.container
  %table.table.table-hover
    %thead
      %tr
        %th Category
        %th Product Name
        %th Details
        %th Price
        %th{:colspan => "3"}
    %tbody
      - @products.each do |product|
        %tr
          %td= product.category.category_name
          %td= product.product_name
          %td= product.about
          %td= product.price
          

app/views/products/show.html.haml
.container
  %table.table.table-hover
    %tr
      %td
        %strong ProductName:
      %td
      %td
        = @product.product_name
    %tr
      %td
        %strong Category:
      %td
      %td
        = @product.category.category_name
    %tr
      %td
        %strong Price:
      %td
      %td
        = @product.price
    %tr
      %td
        %strong Colours:
      %td
      %td
        - @product.colours.distinct.each do |colour|
          = colour.colour
          %br/
    %tr
      %td
        %strong Sizes:
      %td
      %td
        - @product.sizes.distinct.each do |size|
          = size.size
          %br/
    %tr
      %th
      %th= link_to 'View Quantity',quantities_path(product: @product)
      %th= link_to 'Add colour and size',new_quantity_path(product: @product) 
      %th= link_to image_tag("addimg.jpeg", size:"40x40", title: "Add Images"), new_image_path(product: @product)
      %th= link_to image_tag("img.png", size:"40x40", title: "View Images"), images_path(product: @product)
      - @images.each do |form|
        %tr
          %td
            = form.colour.colour
          %td
          %td
            = image_tag (form.image.thumb.url), class: :picture
          %td